#!/usr/bin/env python3

import sys
import os.path

try:
    import cxxtest.cxxtestgen
except ImportError:
    currdir = os.path.dirname(os.path.abspath(__file__))

    if sys.version_info < (3,0):
        sys.path.append( os.path.abspath( os.path.sep.join([currdir, '..']) ) )
    else:
        sys.path.append( os.path.abspath('/home/bb/Cpp_training/cxxtest-4.3/python/python3') )

    import cxxtest.cxxtestgen

cxxtest.cxxtestgen.main()